### ISSUE TITLE
Internal state of assets is not updated after an atlas texture change

### ISSUE THREAD

**Issue by boniatillo-com** [boniatillo-com/PhaserEditor#1]
Phaser Editor build an internal model of the assets textures and information.

When the texture atlas is changed, the assets internal state is not updated, so you can get wrong textures on the Assets explorer or Canvas scenes. Actually, the texture is updated but not the frame bounds in the atlas, so you will see the sprites with weird images.

A work around is to force a build when you add or remove images from the atlas:

1. Change the atlas.
2. In main menu, select `Project >  Clean...` It opens a dialog like this:
![cleanprojects](https://cloud.githubusercontent.com/assets/12187299/16414219/75415c50-3d04-11e6-967c-10efe35f7bb0.png)
3. Press OK to clean (re-build) all the projects, or select the project you are working with.

With the above steps the internal model of the assets is updated so the sprites in the Assets view and the Canvas scenes of your project will be updated as well.

A shortcut to open the Clean dialog quickly is to type `Ctrl+3` and `clean`, then `ENTER`. It uses the Quick Access field. Or you can open the preferences `Main menu > Window > Preferences > General > Keys` and look for the `Clean` command and assign a new key shortcut, like `Ctrl+0`, then when you want to clean the project just press `Ctrl+0`.

**Comment by samsstuff** [comment]
Hey thanks for this Arian, anyone who used eclipse for android or libgdx or other projects should be aware of clean projects already as this is normal routine for us but is good for those who never used it before to update and clean projects :)
I had a dumb moment when this first happened to me but remembered I was in eclipse and did it lol
Thanks for the shortcuts though I never used them before to clean stuff

**Comment by boniatillo-com** [comment]
Thanks Sam, this is already fixed for the next release, together with other similar bugs. If you find any kind of problem like this you are welcome to post it :)
