### ISSUE TITLE
Enhancement: Dragging objects along an axis

### ISSUE THREAD

**Issue by ponderboy** [boniatillo-com/PhaserEditor#24]
At the moment I have to rearrange my scene (a river) and have to arrange everything tightly. So I basically have to drag everything along the x axis. 

In Photoshop and Illustrator you can drag elements along an axis or scale proportionally when using the shift key along. Something similar in PhaserEditor could be helpful.

**Comment by boniatillo-com** [comment]
Good one. Let me think a way to do it with Phaser Editor.

**Comment by boniatillo-com** [comment]
Maybe with Move handlers, similar to other editors like Unity.

**Comment by boniatillo-com** [comment]
Ok, implemented by pressing the shift key, as requested.
