### ISSUE TITLE
Autocomplete across scripts

### ISSUE THREAD

**Issue by Remixful** [boniatillo-com/PhaserEditor#25]
Hello, @boniatillo-com! So far I'm loving Phaser Editor and it really is helping me in learning html5 game development. I don't know what I'd do without it. I am definitely considering purchasing it~

One problem I'm having though is the autocomplete won't work across other scripts in my projects.
Example:
a.js: 
```
//Load b.js

game = new Phaser.Game()
```
b.js:
`game. //no autocomplete shows :(`

Is there a way to fix this?
If not please make this is a feature!

Thanks in advance

**Comment by boniatillo-com** [comment]
Hi @Remixful 

Auto-completion across scripts is supported by the editor. I just tried your example and it works. If you like you can attach your project here and I can see inside it.

JavaScript auto-completion is not perfect, and you have to follow certain rules: 

phasereditor.boniatillo.com/blog/quick-start/030-coding-js-editor

**Comment by Remixful** [comment]
![image](https://cloud.githubusercontent.com/assets/8620268/23442334/d0448278-fdf5-11e6-9446-900ed333b2f5.png)
![image](https://cloud.githubusercontent.com/assets/8620268/23442341/dbc73a0a-fdf5-11e6-952d-651877d6e8c8.png)

**Comment by boniatillo-com** [comment]
Try with declaring the game var in the global scope:

![image](https://cloud.githubusercontent.com/assets/12187299/23461169/d22f39e6-fe56-11e6-8035-bdc97c14d2e0.png)

By the way, auto completion is not going to work very well inside the `preload` method of your code. You should use state inheritance or the global game object to access to the object factory (`game.add`), the loader (`game.load`) and ther other systems, `this.add` is not going to work.

**Comment by Remixful** [comment]
Everything works now, appreciate the feedback!
