### ISSUE TITLE
Feature Request: Support for Phaser.Text in editor

### ISSUE THREAD

**Issue by tomb-pss** [boniatillo-com/PhaserEditor#27]
It would be excellent if one could create text objects the same way as Sprites in the scene editor.

[https://phaser.io/docs/2.6.2/Phaser.Text.html](https://phaser.io/docs/2.6.2/Phaser.Text.html)

**Comment by boniatillo-com** [comment]
Yes, it is on plan: https://github.com/boniatillo-com/PhaserEditor/projects/1#card-1272997

Maybe bitmap fonts first, and later common texts. The problem with common text is the webfonts, I should do a research about to use webfonts on desktop applications.

**Comment by tomb-pss** [comment]
Ok great - glad it's on the roadmap!

Personally, I'm more interested in common text than bitmapped fonts (better for localization). For an initial version of the feature, it might be worth considering just using a fallback (like Arial or something) in the editor if the user specifies a webfont. The important thing is being able to place text in a UI scene.

**Comment by boniatillo-com** [comment]
Working on this ;-)

@1078559858

![image](https://user-images.githubusercontent.com/12187299/31033801-7a33e02c-a52f-11e7-8daf-98f4eb6b0d4c.png)

**Comment by antn9x** [comment]
It's good news.

**Comment by 1078559858** [comment]
Does it working in the version 1.4.3 ? 
it's good fine!

**Comment by boniatillo-com** [comment]
I just pushed the last changes, now it is complete, you can test it from the sources. In this week I should release the v1.4.3 with this changes and others.
