### ISSUE TITLE
Linux starting issue still there

### ISSUE THREAD

**Issue by samsstuff** [boniatillo-com/PhaserEditor#28]
Hello Arian just thought I'd let you know the loading issue still is there where it hangs and never loads.
No big deal for me I just create my own script to load it but I still have to use -clearPersistedState to get it to load properly.
It's late so I didn't have time to fool around with it yet I just installed the dark theme into it (I use a dark theme in linux)and fooled around with creating a new project.
So far it is great and a ton of new toys to play with :)
Just thought I would let you know about the launch issue

To help out any linux users having the same issue here is a little bash script I wrote so you won't have this same issue.
Create a text file I named mine: loadNewPhaser.sh

in that file paste this:
#/bin/bash
/home/samstoy/PhaserEditor14preview/PhaserEditor -clearPersistedState
save it into the same folder where you put the editor
where the link is: /home/samstoy/PhaserEditor14preview/
change this to your folder where you put the phaser editor at in your directory.
right click on the file and go to preferences and then permissions and click the checkbox to make it executable.
You can then either load it through the terminal orrrrr the easy way, create a launcher on your panel in the command section add a link to the loadNewPhaser.sh file add a name if you want and add an icon if you want, I made my own.
It'll load from your panel this way, or create a desktop file in your .local/share/applications folder if you want it to show up in the normal menu 
Something like this:
create another text file call it something like PhaserEditor.desktop
in it add something like this:
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
NoDisplay=true
GenericName=Phaser Editor
Exec=/home/samstoy/PhaserEditor14preview/loadNewPhaser.sh %f
Icon=/home/samstoy/phasereditor.png
Name=Phaser
Comment=Link to load the editor
Categories=Development;
StartupNotify=true
TryExec=Phaser 

of course change it again to where you put the loadNewPhaser.sh file and change the icon localtion and whatever esle you need to, then save it, it should show up in your menu under the development.

I just create a launcher on the panel it is easier and I use the panel for most stuff.

Hope it helps some folks out.
Remember I use manjaro arch based with xfce so distros and de's might differ, but most work pretty much the same in linux.

Once I get some sleep and get some more time to play with it more I'll let you know of any more bugs that arise.
But so far that is the only one.
Take care Arian your doing a great job.
Sam

**Comment by boniatillo-com** [comment]
Thanks Sam.

Testing this again. I will upload an update if I fix the bug.

**Comment by boniatillo-com** [comment]
Hello @samsstuff 

There is a new Phaser Editor version (1.4.2), please if you plan to update to that version let's remove these lines:

```
-persistState
false
```

...from the `PhaserEditor.ini` file and tell me if this issue continues.

Thanks in advance!

**Comment by samsstuff** [comment]
Hello Arian
First of all glad to see your ok after that nightmare irma, I was keeping up with it on cnn.
I tried to update and got an error here it is

An error occurred while collecting items to be installed
session context was:(profile=profile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://phasereditor.boniatillo.com/updates/1.4.0/plugins/org.eclipse.jgit_4.8.0.201706111038-r.jar.
http://phasereditor.boniatillo.com/updates/1.4.0/plugins/org.eclipse.jgit_4.8.0.201706111038-r.jar
Artifact not found: http://phasereditor.boniatillo.com/updates/1.4.0/plugins/org.eclipse.ui.intro.universal_3.3.100.v20170515-1335.jar.
http://phasereditor.boniatillo.com/updates/1.4.0/plugins/org.eclipse.ui.intro.universal_3.3.100.v20170515-1335.jar

Do you think it is better just to do a clean install instead since your upgrading eclipse itself?
Sam

**Comment by boniatillo-com** [comment]
No please keep updating it, let me test on linux.

**Comment by boniatillo-com** [comment]
Are you updating from v1.4.1 or v1.4.0?

**Comment by samsstuff** [comment]
Phaser Editor v1.4.0-preview.2

**Comment by boniatillo-com** [comment]
Please can you try again?

**Comment by samsstuff** [comment]
in the installed software section it shows 1.4.1.20170628

**Comment by boniatillo-com** [comment]
ok opening linux... (and thanks yes I am fine, and family too :) )

**Comment by samsstuff** [comment]
thats good to here I was worried about you folks
ok it updated that time but now it wont load lol
I removed the persistate state lines and tried again still no load
I opened it through the terminal to get what was going on here is the printout

java.lang.IllegalStateException: Could not create a builder for the system bundle.
	at org.eclipse.osgi.storage.Storage.checkSystemBundle(Storage.java:290)
	at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:90)
	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:68)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:303)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: org.osgi.framework.BundleException: A bundle is already installed with the name "org.eclipse.osgi" and version "3.12.0.v20170512-1932"
	at org.eclipse.osgi.container.ModuleContainer.update(ModuleContainer.java:341)
	at org.eclipse.osgi.storage.Storage.checkSystemBundle(Storage.java:281)
	... 13 more

**Comment by boniatillo-com** [comment]
What a s... try with the -clean argument.

**Comment by samsstuff** [comment]
in the ini file?
or the terminal?

**Comment by boniatillo-com** [comment]
in terminal... but I am updating here now, I will tell you my findings.

**Comment by samsstuff** [comment]
alright I woke up and just added it to the ini file lol
It now works.here it is

![itworks](https://user-images.githubusercontent.com/19275499/30296218-627bb184-9711-11e7-99f0-b4c5118092c5.png)

**Comment by samsstuff** [comment]
I put it in the ini instead and it opened no problem through the terminal let me try without the terminal but I'll remove -clean first

**Comment by boniatillo-com** [comment]
Great! That Eclipse update is getting issues with the plugins cache. It is an update from Neon to Oxygen and it is a some way drastic! Actually, it cannot be done from Mars to Oxygen. I will mention it on the release notes.

**Comment by boniatillo-com** [comment]
Ok please test.

**Comment by samsstuff** [comment]
ok were all good now :) 
It loads without the persisitate false now also and I see you fixed the chains highlight also nice color :)
I loaded it without the terminal from the launcher I created also.
I am using manjaro (arch base) so it should load in any other system if it loads in here.

**Comment by samsstuff** [comment]
it also retained my theme I downloaded also which surprised me I thought I would lose that going to a different version of eclipse :)

**Comment by boniatillo-com** [comment]
(by the way, my test updating from 1.4.0 to 1.4.2 worked on linux, maybe it was a cache problem in your local installation, anyway, I mentioned it in the release notes because other users may have the same issue)

**Comment by samsstuff** [comment]
alright if you try and use the run menu there is nothing to choose to run it with (I never use that anyhow) but the globe still works fine which is what I always use anyhow, just in case anyone ask about that, it pops up external tools with nothing but you can config it to load anything you want in case anyone wants to pick a different browser or anything else

**Comment by samsstuff** [comment]
oh ya are you going to update to version 3 phaser once the final version comes out?
If not it's no issue I can add it anyhow, I want to use it for a game i'm making for facebook since they allow webgl finally besides unity

**Comment by samsstuff** [comment]
I'm shocked you got power still

**Comment by boniatillo-com** [comment]
Regarding the Run configurations, I created an issue for it:

https://github.com/boniatillo-com/PhaserEditor/issues/48

Yes, I plan to support Phaser v3 when the API gets stable.

Probably I will create a new type of project, a Phaser 3 project with basic features and then start the complete migration to Phaser 3.

**Comment by boniatillo-com** [comment]
> I'm shocked you got power still

do you mean electric power after Irma? well, I am in Isla de la Juventud, it is a "big" island in the south of Cuba, and the wind was very soft.

**Comment by samsstuff** [comment]
great I stopped all other projects to do the artwork for that one game, a hidden object one for facebook but it takes months of artwork to complete, probably get most of it done when phaser 3 is finalized

Isla de la Juventud is a beautiful island I just checked it out, your living in paradise

**Comment by boniatillo-com** [comment]
It sounds huge! it will be great to feature it in the website. Yes I think Phaser 3 will need some time to be ready for production.

Yes the island is beautiful, specially going to the south, it is like virgin, but with lot of mosquitos hahaha. I like the place :), I am from Havana but this place is very quiet, I can go walking or in bicycle everywhere.

**Comment by samsstuff** [comment]
nice, I'm in Canada we get snow lol
I'm so tired of snow lol
That would be cool if you featured it, it's just going to take me a bit to create it, at least 100 background images then I'll update it with more later on, probably 10 at a time.
Plus ten billion items to add in those image to pick from haha
I just want to use the speed of webgl with this one and the new features of timeline and the new tweening will help a ton with all the coding.
We get those pesky mosquitos up here also along with the west nile virus and those biting black flies which you probably don't get thankfully if your in a low humid climate
Alright back to work for me take care Arian glad to see you and the family are safe I was worried about you folk

**Comment by boniatillo-com** [comment]
It is like that, I love snow, I enjoyed it in Serbia hahaha. Ok see you, that game will be the bible of the hidden objects games haha.

**Comment by boniatillo-com** [comment]
Fixed in v1.4.3 (already released)
