### ISSUE TITLE
Groups marked as public are exported with type Phaser.Sprite in TypeScript

### ISSUE THREAD

**Issue by tomb-pss** [boniatillo-com/PhaserEditor#29]
Thanks for the new release - it's looking good!

I have run into one bug with the TypeScript code generation: If I have a scene with a group that I mark as public, the property is given the type Phaser.Sprite, which won't compile.

**Comment by boniatillo-com** [comment]
Working on this, I will upload an update. Thanks.

**Comment by boniatillo-com** [comment]
Fixed.

Please check for updates and install them: `Help > Check for Updates`.

Tell me if it works to close the issues.

**Comment by tomb-pss** [comment]
Yup - it is working correctly, now. Thanks!

**Comment by boniatillo-com** [comment]
Good! I close this. Waiting for more issues :)
