### ISSUE TITLE
It's not possible to install new software

### ISSUE THREAD

**Issue by free8bit** [boniatillo-com/PhaserEditor#3]
In a normal eclipse build it's possible to install new software from Help > Install New Software.
For example I would like to install EGit, but I can't.
This is an enhancement more than an issue.

**Comment by boniatillo-com** [comment]
Yes, I had in plan to add it in the last version, but in the last minute I realized that to include the Eclipse Marketplace I should include other "garbage" plugins  so I decided to do it with more time to test it is going to work well. Thanks.

**Comment by boniatillo-com** [comment]
@free8bit

In the latest release you can install new softwares via marketplace or update site. 

http://phasereditor.boniatillo.com/blog/2016/12/phaser-editor-v130-released
