### ISSUE TITLE
Couldn't activate v1.3.0

### ISSUE THREAD

**Issue by llin96** [boniatillo-com/PhaserEditor#30]
I always get the error "ConnectException: Connection timed out: connect" when I am trying to activate Phaser Editor 1.3.0, while my internet connection is good.

**Comment by llin96** [comment]
One more question, how to upgrade from v1.2.1 to v1.3.0? my 1.2.1 was activated.

**Comment by boniatillo-com** [comment]
Hi @llin96 

Are you connecting with a proxy? Also please send us an email with your key or purchase email, to check it is working well.

**Comment by boniatillo-com** [comment]
Also please try to open the Eclipse Marketplace:

Help > Eclipse Marketplase

If it opens well it means that your internet connection is well configured in the editor.

**Comment by boniatillo-com** [comment]
About the other question, upgrade is only available from v1.3.0 forward.

**Comment by boniatillo-com** [comment]
Can I close this?

**Comment by llin96** [comment]
I thought I've sent you my purchase key, I will send you later.

**Comment by boniatillo-com** [comment]
I will close this. In any case you can open it again.
