### ISSUE TITLE
FeatureRequest: Change sprite name for sprite prefab instance.

### ISSUE THREAD

**Issue by nicloay** [boniatillo-com/PhaserEditor#34]
here is what i'm doing

1. Create new Sprite Prefab *mySprite.canvas*
2. Create new Group Prefab *myGroup*
3. Add 2 instances of mySprite to the canvas.
4. I'd like to change sprite for 2d instance  (command+T hot key which *Change Sprite Texture*)
5. in popup window select another sprite.
6. getting the error *the texture of the prefab instance 'instance name' is read-only*

**Comment by boniatillo-com** [comment]
Hi @nicloay 

By default you only can change the position of a prefab instance. To change any other property you have to declare it in the ``override`` property. In this case you have to include``texture`` in the list.

![Override properties](http://phasereditor.boniatillo.com/blog/content/images/20170410163533-OverridePrefabInstanceProperty.png)

Read about it in the release notes:

http://phasereditor.boniatillo.com/blog/2017/04/release-v140-preview

Look for the section [Change/reset prefab instance properties](http://phasereditor.boniatillo.com/blog/2017/04/release-v140-preview#change-prefab-properties).

**Comment by boniatillo-com** [comment]
By the way, remember that if what you want is to change the texture for all the prefab instances, then you should do it in the prefab file itself, then the change is propagated in all the instances, excluding those who are overriding the ``texture`` property.

**Comment by nicloay** [comment]
Thanks a lot!

Works like a charm. sorry that i've missed that page.
It's just a bit confusing find info in blog posts =).

**Comment by boniatillo-com** [comment]
Great!

Yes, the documentation for that preview version is not written yet, and at the same time, that prefab feature is a bit different to other editors like Unity. So please do not hesitate to add new issues.
