### ISSUE TITLE
Elevated rights to run on Mint [Linux]

### ISSUE THREAD

**Issue by boniatillo-com** [boniatillo-com/PhaserEditor#4]
From Glenn Gartner via email:

...On Linux Mint (17.3 Cinnamon), elevated rights are required to run the editor. After a few attempts to run the SetExecPermission.sh script, I can now open the editor as a non-su, but the chains crash with: 

![pe_error_linux_mint_su_permissions](https://cloud.githubusercontent.com/assets/12187299/16698359/eb3683ee-451b-11e6-8397-447d460d5c1c.png)

and javascript tooling crashes with:

![pe_error_linux_mint_su_permissions_2](https://cloud.githubusercontent.com/assets/12187299/16698364/ef2cd91c-451b-11e6-84ac-7305a783903a.png)

Any thoughts on getting this to work on Linux, as a non-su? I don't like running programs as su. 

Thanks, and great work so far.

**Comment by boniatillo-com** [comment]
Hum... very strange... I know it worked for other linux users, I tested it on ubuntu and it works fine too, without need to `su` it.

So do you mean it runs with no error if you execute it with sudo?

The `SetExecPermission.sh` script is needed to give execution permissions to some programs like `ffmpeg`, `optipng`, `java`, etc... that are bundled inside the editor. But I don't think it has relation with the errors you are posting here. It seems like are missing some files.

Please execute the editor in this way:

```
$ ./PhaserEditor -consoleLog
```

and send me all what it prints to console until you get the errors.

Thanks for your feedback.

**Comment by samsstuff** [comment]
alrighty then I just had this same error with the updated version I forgot to add the PhaserEditor-PhaserBundle-master folder into the main folder of phaser editor it had nothing to read for chains and once I re-added it back into the folder voila it worked with no issues again just download the phaser budle in this github extract it and shove the folder into the same folder the editor is in, it throws out a crap load of errors if you don't, it would not even bring up the preference page in the settings, I had the last one to search for that folder for updates.
I went through the new bundle master last night with the older version it was missing some examples in it for chains and threw errors for those I just re-added those examples again and it worked again with no errors (like pong.js) it's missing and a few more, quick way grab the older example folder paste into the same folder as the new one skip all duplicates (I'm old and lazy now to go through them all lol ) 
But yup that worked for me got rid of the above screenshots right away.

**Comment by boniatillo-com** [comment]
Hi Sam thanks for your tips. I will try to reproduce this situation.

**Comment by boniatillo-com** [comment]
I created a new issue for this:

https://github.com/boniatillo-com/PhaserEditor/issues/7
