### ISSUE TITLE
varName of the sprite created by copy-paste (ctrl+c, ctrl+v) is changed when it is moved in hierarchy

### ISSUE THREAD

**Issue by mulovad** [boniatillo-com/PhaserEditor#40]
1. create sprite A
2. create Sprite B (by copying sprite A by ctrl+c, ctrl+v )
3. change the sprite B's varName
4. move the sprite B
then the sprite B's varName is reverted.

**Comment by boniatillo-com** [comment]
I cannot reproduce this issue.

In point 4 do you mean to move the sprite B into other group?

**Comment by mulovad** [comment]
Let me introduce an example.
1. Create group1, group2.
2. Create 2 sprites named 'p1c1', 'p2c2' placed on group1
3. Move all sprites to group2
then 'p1c2' is renamed to 'p1c'

**Comment by boniatillo-com** [comment]
Yes, I can reproduce it now. 

It has to be about the automatic numbering when you create a new sprite.

**Comment by boniatillo-com** [comment]
Fixed.
