### ISSUE TITLE
[Linux] Editor doesn't start

### ISSUE THREAD

**Issue by ventoh** [boniatillo-com/PhaserEditor#41]
Hello,

I have already tried to boot the editor with clearPersistedState and persistState=false but it won't start.
I've got this error on PhaserEditor 1.3.0:

Built-in Phaser version: 2.6.2
Build Phaser JSDoc 262
Building chains 619ms
Loaded org.eclipse.wst.jsdt.internal.ui.javaeditor.CompilationUnitEditor@45635ae1 2042
Attempt to unlock mutex that was not locked

and I've got this error on PhaseEditor 1.4.0 preview

Plugin.start phasereditor.lic...
Starting JavaFX runtime...done
Attempt to unlock mutex that was not locked

I'm using  elementary OS Freya based on Ubuntu 14.04

**Comment by boniatillo-com** [comment]
Hi,

Is it the first time you execute the editor?

**Comment by ventoh** [comment]
Yes, it is the first time.

**Comment by boniatillo-com** [comment]
Phaser Editor requires gtk2 by default. Do you have it installed in your system?

Please try this in a terminal window:

```
> cd /path/to/Phaser Editor
> export SWT_GTK3=0
> ./PhaserEditor
```

**Comment by ventoh** [comment]
ok, elementary OS it's not gtk related distro. 

I'm trying to install gtk and thus i have issued the command:

apt-get install gtk2.0

but the problem is not solved. Please, can you address me on what gtk packages are required?

**Comment by boniatillo-com** [comment]
But does it installed it?

At this moment I do not have an ubuntu machine here, I have a debian one and the way to install gtk2 is:

```
apt-get install libgtk2.0
```

Maybe you can try with it.

**Comment by ventoh** [comment]
Sure, libs are installed.

Just tried on ubuntu 16.10 in virtualbox and it working. So the issue is on Elementary Freya.

I've issued this commands:

```
$dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64                            3.14.15-0ubuntu1~14.04~ricotz1                                  amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                                3.14.15-0ubuntu1~14.04~ricotz1                                  amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                             3.14.15-0ubuntu1~14.04~ricotz1                                  all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64                          3.14.15-0ubuntu1~14.04~ricotz1                                  amd64        development files for the GTK+ library
ii  libgtk2-perl                                2:1.249-2                                                       amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64                           2.24.23-0ubuntu1.4                                              amd64        GTK+ graphical user interface library
ii  libgtk2.0-0-dbg                             2.24.23-0ubuntu1.4                                              amd64        GTK+ libraries and debugging symbols
ii  libgtk2.0-bin                               2.24.23-0ubuntu1.4                                              amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-cil                               2.12.10-5                                                       amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-cil-dev                           2.12.10-5                                                       amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common                            2.24.23-0ubuntu1.4                                              all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-dev                               2.24.23-0ubuntu1.4                                              amd64        development files for the GTK+ library
ii  libgtk2.0-doc                               2.24.23-0ubuntu1.4                                              all          documentation for the GTK+ graphical user interface library

```

then

```
$pkg-config --modversion gtk+-2.0
2.24.23

```

```
$pkg-config --modversion gtk+-3.0
3.14.15
```

Any hint?

**Comment by boniatillo-com** [comment]
No, no hint for now. Sorry, I should go away now, tomorrow I can continue investigating.

**Comment by ventoh** [comment]
The issue  seems to be related to gtk2.0 on ubuntu 14.04 (trusty and elementary os)

https://bugs.launchpad.net/elementaryos/+bug/1518373

**Comment by samsstuff** [comment]
Isn't elementaryOS 0.4 loki based on ubuntu 16?
Wouldn't upgrading it fix this issue and give you a more updated system?
trusty is getting pretty old now, unless you have a very old amd that might cause an issue with the upgrade, but it looks like ubuntu 16  works in vb so that shouldn't be an issue.
I'm on manjaro and sometimes use mint based on ubuntu 16, both don't give me any issues, unless it's just something in elementary itself (besides the issue you stated)

**Comment by ventoh** [comment]
elementary Freya  has Long Term Support until 2019 and as i hate the updates i would like to keep freya until that date if possibile.
Also freya can't be upgraded to loki. A new fresh install is required. Too much time is needed to reconfigure my system from scratch :(
I will try if will be possibile to recompile gtk with the backport.
Thank you for your support.

**Comment by boniatillo-com** [comment]
I test Phaser Editor on ubuntu 14.04, so I think that ubuntu version is not the problem, else a configuration of your current installation.

Maybe you can try with a fresh install of Freya on virtualbox.

**Comment by ventoh** [comment]
Problem occours only on gtk 2.24.23 and glib>2.40 Maybe you have tried on normal ubuntu neither LTS  or updated. 
Lastest updates on Ubuntu 14.04  LTS have that libraries version. 

Anyway i solved in this way:

Get source packages

```
sudo apt-get install build-essential
apt-get build-dep libgtk2.0-common 
cd gtk+2.0-2.24.23/

```
edit gdk/gdk.c and find the code 
```
if (gdk_threads_mutex) 
        g_mutex_unlock (gdk_threads_mutex);
```

replace with
```
if (gdk_threads_mutex) {
        g_mutex_trylock (gdk_threads_mutex);
        g_mutex_unlock (gdk_threads_mutex);
}
```
  
recompile the packages with
`debuild -us -uc -b`

force install of the news packages
```
sudo dpkg -i ../libgtk2.0-common_2.24.23-0ubuntu1.4_all.deb
sudo dpkg -i ../libgtk2.0-0_2.24.23-0ubuntu1.4_amd64.deb
```

now ./PhaseEditor work like a sharm

This solve all problems about gtk2.0 mutex error on elementary Os e Ubuntu. Thank to open source :)

**Comment by boniatillo-com** [comment]
WAO!!!! That is a workaround hahaha! I am happy it works for you now.

**Comment by boniatillo-com** [comment]
Java 9 is going to be released in september and will provide gtk3 support so I think lot of issues related to linux will be fixed.
