### ISSUE TITLE
Activation product fail !

### ISSUE THREAD

**Issue by anden007** [boniatillo-com/PhaserEditor#49]
I had purchase a lifetime license key for v1.3.0, but the license info losted after updated to v1.4.2.
"UnknownHostException: api.gumroad.com" error occurred when I reuse the key to activate.
please help ! 
-------------------------------------------------------
tips: I'm in china，maybe the api.gumroad.com is blocked...How can I activate v1.4.2, waiting on line .

**Comment by boniatillo-com** [comment]
Please email us to developers@boniatillo.com
