### ISSUE TITLE
Offer alternative builds to zip (due to chmod)

### ISSUE THREAD

**Issue by cookiengineer** [boniatillo-com/PhaserEditor#5]
On GNU/Linux systems the zip file will lead to users having trouble running Phaser.

Necessary steps:

1) Build a README.txt that shows what VM exit code 13 means
2) chmod +x ./PhaserEditor
3) chmod +x ./jre/bin/java

Then people can execute the PhaserEditor by manually entering the command dump (having to modify all `\n` before, so it's pain to do). Afterwards another error occurs, will open a separate issue.

edit:// issue is fatal error in gdk_display_open: #6

**Comment by cookiengineer** [comment]
Damn it, I just found this other issue (#4) and realized that this seems to fix the problem.

Quick suggestion: Name the script `start.sh` and inser the above chmods + ./PhaserEditor in it, so people not familiar with the Editor know what to do.

**Comment by boniatillo-com** [comment]
Thanks, I will consider your suggestion for the next release.

**Comment by boniatillo-com** [comment]
Added a README.TXT file to explain how to start the editor.
