### ISSUE TITLE
Phaser CE support? (phaser community edition)

### ISSUE THREAD

**Issue by PKrawczynski** [boniatillo-com/PhaserEditor#57]
Does editor support phaser community edition easily? Can it be added as altenative to 2.6.2 runtime since phaser 2.6.2 was probably last 2.x release and community only provides/fixes improvements right now as project owner has moved onto 3.x versions.

**Comment by boniatillo-com** [comment]
We don't plan to support Phaser CE. We have limited time and we have to dedicate all the effort to migrate to Phaser 3 as soon as a stable version is released, or before.

However, I think many of the API supported by Phaser Editor is compatible with Phaser CE, so you can just work with the editor but load the Phaser CE runtime by yourself.

**Comment by PKrawczynski** [comment]
>we have to dedicate all the effort to migrate to Phaser 3 as soon as a stable version is released, or before.

@boniatillo-com alright, that's actually amazing news. I'd put that in faq somewhere just in case people will wonder, as I've thought this wouldn't happen.

Keeping fingers crossed for you.

**Comment by boniatillo-com** [comment]
@PKrawczynski thanks! Yes, I have to create a FAQ.
