### ISSUE TITLE
How to change texture of Sprite on canvas?

### ISSUE THREAD

**Issue by antn9x** [boniatillo-com/PhaserEditor#58]
I need a guide for change texture file of Sprite and Group on canvas design.
Please help.

**Comment by boniatillo-com** [comment]
Take a look at the editor docs:

http://phasereditor.boniatillo.com/docs/canvas.html#texture

You can replace the texture of a single sprite or replace the texture in all the sprites of the project.

**Comment by antn9x** [comment]
Thank you, I got it.
