### ISSUE TITLE
How can I ignore folder from search assets?

### ISSUE THREAD

**Issue by antn9x** [boniatillo-com/PhaserEditor#59]
I don't want  search asset for pack file from some folders like node_modules, src, build, ... 
How can I settings for ignore those folders?

**Comment by boniatillo-com** [comment]
In this issue I just mentioned that I have to think on it:

https://github.com/boniatillo-com/PhaserEditor/issues/54

**Comment by boniatillo-com** [comment]
@antn9x You can try the method explained here:

https://github.com/boniatillo-com/PhaserEditor/issues/54#issuecomment-335292190

Please tell me if it works for you.

**Comment by boniatillo-com** [comment]
It is a workaround until I implement a better solution.

**Comment by boniatillo-com** [comment]
Done. Now it looks for the files in the folder tree where the asset pack file is placed.
