### ISSUE TITLE
Fatal error (gdk_display_open)

### ISSUE THREAD

**Issue by cookiengineer** [boniatillo-com/PhaserEditor#6]
In a GNOME3 environment (Arch + Ubuntu) a fatal error occurs in the bundled java runtime:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffa182812b7, pid=4443, tid=0x00007ffaa81b1700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgdk-x11-2.0.so.0+0x4e2b7]  gdk_display_open+0x57
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/cookiengineer/Downloads/PhaserEditor/hs_err_pid4443.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Any hints on what might cause the problem?

**Comment by boniatillo-com** [comment]
Hi @cookiengineer 

Maybe it is about to the GTK version.

Please check this issue in the old repo:

https://bitbucket.org/boniatillo/phasereditor/issues/2/pe-runs-very-slowly-freeze-infinite

(I should migrate all those issues to github, but it results that now Bitbucket is another service denied to Cuban IPs and I cannot access Bitbucket anymore)

If it does not work please write it here. Sorry I cannot help more now, I am in hollidays, I will be back next week.

**Comment by boniatillo-com** [comment]
So it worked for you?

**Comment by cookiengineer** [comment]
In the bitbucket issue it states that I have to open PhaserEditor and go to the About Dialog. But, due to the fatal error and segfault I can't open PhaserEditor.

**Comment by samsstuff** [comment]
the main problem from reading your post is this one line
C  [libgdk-x11-2.0.so.0+0x4e2b7]  gdk_display_open+0x57
if you go here they had the same issue on debian: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=430736
there is one suggestion in there but also another with the glib
"From the prior crash log we can see that glibc 2.13 is installed.  
Can you please upgrade glibc to at least 2.14 and verify?"

if you use the command 
ldd --version
it will show you what version you have mine is 2.19

There is some other ideas to fix this but the main one seems to be the glibc issue

I have this running on linux mint 17.3 with no issues with oracle java version 
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Hope it helps you help somewhat
Sam

**Comment by boniatillo-com** [comment]
Thanks @samstuff! I hope it will help to @cookiengineer to solve the issue.

By the way, also try installing gtk2, Phaser Editor requires it (forced by JavaFX).
