### ISSUE TITLE
Restarting state throws a lot of errors because of preloading.

### ISSUE THREAD

**Issue by PKrawczynski** [boniatillo-com/PhaserEditor#60]
Example from error console:
```
VM296:1 Uncaught SyntaxError: Identifier 'GoblinSpearPrefab' has already been declared
    at <anonymous>:1:1
    at Phaser.Loader.fileComplete (phaser.js:75096)
    at XMLHttpRequest.xhr.onload (phaser.js:74672)
```

This only happens when I reload state that has function to preload assets.
`this.load.pack('minimal', 'assets/pack.json');`

Because I drag and drop assets on canvas above function is automatically included in preload function of state which is called each time state is reloaded wchich results in a lot of console errors.

Another example was when I was using assets from that pack in "main menu" and "level" which lead to level throwing that error (as minimal pack was loaded twice)

**Comment by PKrawczynski** [comment]
I've hotfixed issue by having my "Boot state":

```
preload () {
		this.load.pack('boot', 'assets/pack.json'); //this is injected in BEFORE preload in canvas file.
		this.load.pack('minimal', 'assets/pack.json');
}
```

and by having my "Level state" inject :
```
preload () {
	return;//this is injected in BEFORE preload in canvas file.
	this.load.pack('minimal', 'assets/pack.json');
	}
```

All is well when I do that but it is massive workaround.

**Comment by boniatillo-com** [comment]
Hi @PKrawczynski 

I see two issues here:

1- We need a better control of what to load.
2- You are loading the script "GoblinSpearPrefab" twice.

The first issue is solved: https://github.com/boniatillo-com/PhaserEditor/issues/51#issuecomment-333828255 and will be ready for the next release (I hope this week!)

I think you can fix the other issue because from the error I conclude that you are declaring the same class twice. Are you using JavaScript 6? So the solution could be to place the "script" assets in a different pack section, separated from the visual assets.

**Comment by PKrawczynski** [comment]
1. Definitely. Proposed solution looks very nice imho - suits larger projects just fine. 
2. It's loaded twice as goblin prefab is used in two separate canvas scenes and thats why preloading of that specific asset has happened twice (because of auto declared preloading). However It will be fixed by your solution (or my hacky workaround for now).

As for naming I'm avoiding collisions by using affixes (GoblinSprite.canvas, GoblinSpritePrefab.png, GoblinSpritePrefabScript.js). 

I think we can close this one as it's solved in next release from what I understand. Thank you!

**Comment by boniatillo-com** [comment]
Great, however, I still think that you can avoid the workaround if you load the scripts once. Just put the scripts in a different section, they are not added to the asset pack automatically, you have to do it manually. But if you put the scripts in the same section of the visual assets used in the canvas, then the scripts will be loaded twice.
