### ISSUE TITLE
TypeScript does not compile to Javascript in Phaser Editor 1.4.3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by DavidPesta** [boniatillo-com/PhaserEditor#65]
When I make changes to a .ts file and save, then open the .js file, the changes do not show in the javascript file. When I click the button to run the phaser project, the changes are still not compiled and do not show in the running project.

In the Project tab, Build Automatically is checked.

In Project > Properties > Builders: Phaser Builder and TypeScript Builder are both checked.

**Comment by boniatillo-com** [comment]
Hello I am out of the city, tomorrow i will try to help.

**Comment by boniatillo-com** [comment]
Hi @DavidPesta 

The TypeScript Builder provided by the plugin could be buggy, you can open an issue here: https://github.com/angelozerr/typescript.java

My advice is just to use the TypeScript Compiler directly, for example, with the watch mode:

https://www.typescriptlang.org/docs/handbook/compiler-options.html

```
tsc --watch
```

**Comment by DavidPesta** [comment]
Watch is probably a good solution. It gets around the problem with the plugin for now.

Looking forward to TypeScript by default. You are doing a great job, keep up the great work!

**Comment by boniatillo-com** [comment]
Thanks!
