### ISSUE TITLE
Crash at startup when missing phaser bundle

### ISSUE THREAD

**Issue by boniatillo-com** [boniatillo-com/PhaserEditor#7]
Phaser Editor shows lot of errors if it is linked to a Phaser bundle that was deleted or renamed.

As a workaround, you have different options:
- Put back the phaser bundle.
- Start a new workspace and import the projects.
- Delete the `.metedata` folder of the workspace (as is suggested in the below comment of @samstuff)
- Fix the bundle preference yourself: in your workspace, open the file `.metadata/.plugins/org.eclipse.core.runtime/.settings/phasereditor.inspect.core.prefs`. And change the value of the property `phasereditor.inspect.core.builtInPhaserVersion=false` to `true`. Is simple.

**Comment by samsstuff** [comment]
Hi Arian
another quick fix is just delete the metadata folder in the workspace then re-import the project, that way they don't have to go moving their files over to a new workspace, the whole issue is in that metadata folder, by deleting it and re-importing the project it creates a new metadata folder that fixes the issue, but again the easiest fix, just put the bundle back in the main folder so the same metadata files can read it , there is no need to create a new workspace.
I like just dropping in the bundle master but it is going to create issues with folks that rename it,
Maybe someway of updating through the update window by adding a url link with an install into one directory so it never changes ex: PhaserEditor/PhaserEditor-PhaserBundle-master/
That way it'll keep the metadata files happy, especially if your like me and have 3 workspaces running each with their own metadata folders, after 5 or 6 projects to import it can become a headache.
The easiest solution, put the bundle master back where it belongs lol
A nice way of updating but yup there will be trouble for those not putting it back the same.

**Comment by boniatillo-com** [comment]
Fixed, I will close the issue when the new version is released.

**Comment by boniatillo-com** [comment]
If the bundle is not found it will show this message:

![image](https://cloud.githubusercontent.com/assets/12187299/18891758/b57f8342-84d4-11e6-99c6-6f8f0f94fe43.png)

And fallback to the built in bundle.

**Comment by samsstuff** [comment]
Nice fix :) can't get any plainer than that.

**Comment by boniatillo-com** [comment]
Phaser Bundle is deprecated. Now the editor can be full updated automatically.
