### ISSUE TITLE
I can't download phaser editor even after purchasing????

### ISSUE THREAD

**Issue by xxrosaxx** [boniatillo-com/PhaserEditor#9]
Hi I **bought** phaser editor because it looked great , 
wonderful features and all that but for some reason 
I am forbidden to download it off your server what the heck?.

Id like a download link please for my purchase or a refund if their is no way 
for me to get the software for a year, I can show you my license key if you like too.

I've seen the github link but not able to download anything that is useful 
like an exe or application binary.

**Comment by samsstuff** [comment]
Hello xxrosaxx you should be able to download it here: [http://phasereditor.boniatillo.com/blog/downloads](http://phasereditor.boniatillo.com/blog/downloads)
its a standalone so just extract it (right click extract here) copy or drag the folder into whatever directory you want, click the PhaserEditor.exe (on windows) file or the PhaserEditor bin file in linux it'll ask for a workspace (where you keep your projects) you can create one or it'll create one called workspace for you (I use many so I have different ones, once opened up got to help on the menu and click Phaser Editor Activation put your key in there and you should be good to go.
I use linux so it might be a bit different in which Arien can explain that for you if so.

Just choose which operating system you use, windows or linux and download it form the link I gave you.

Hope this helps you out.

Sam

**Comment by xxrosaxx** [comment]
Oh allright , I had thought so maybe you guys should fix the hosting server : ) if it's at all possible
in your current circumstance . 

Can someone let me know when it's working again?.

**Comment by boniatillo-com** [comment]
Hi @xxrosaxx 

I am contacting with the hosting provider to fix the problem.

Thanks for contact with us, I will let you know when the downloads get available again.

Thanks @samsstuff !!!

**Comment by boniatillo-com** [comment]
The website is back again.
